name: 'Configuration Manager'
type: module
description: 'Allows administrators to manage configuration changes.'
package: Core
# version: VERSION
# core: 8.x
configure: config.sync

# Information added by Drupal.org packaging script on 2017-02-10
version: '8.3.0-alpha1+70-dev'
core: '8.x'
project: 'drupal'
datestamp: 1486770232
